package:
  name: clint
  version: !!str 0.3.7

source:
  fn: clint-0.3.7.tar.gz
  url: https://pypi.python.org/packages/source/c/clint/clint-0.3.7.tar.gz
  md5: 4379c034b978e1542e024de3566ea222
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - clint = clint:main
    #
    # Would create an entry point called clint that calls clint.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - args

  run:
    - python
    - args

test:
  # Python imports
  imports:
    - clint.textui
    - clint
    - clint.packages.colorama
    - clint.packages

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/kennethreitz/clint
  license: 
  summary: 'Python Command-line Application Tools'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
