package:
  name: pdfminer
  version: 20140328

source:
  fn: pdfminer-20140328.tar.gz
  url: https://pypi.python.org/packages/source/p/pdfminer/pdfminer-20140328.tar.gz
#https://pypi.python.org/packages/source/e/ephem/ephem-3.7.5.3.tar.gz#md5=0e33905844e3be5c901c13e5a9c938a3
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - nltk = nltk:main
    #
    # Would create an entry point called nltk that calls nltk.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - setuptools
    - pyyaml

  run:
    - python
    - pyyaml

test:
  # Python imports
  imports:
    - pdfminer
    #- ephem.cities
    #- nltk
    #- nltk.chunk
    #- nltk.tokenize

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://euske.github.io/pdfminer/index.html
  license: MIT License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
