package:
  name: textract
  version: !!str 0.5.1

source:
  fn: textract-0.5.1.tar.gz
  url: https://pypi.python.org/packages/source/t/textract/textract-0.5.1.tar.gz
  md5: a6bf78706e060fa5b803086f557db45e
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - textract = textract:main
    #
    # Would create an entry point called textract that calls textract.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - argcomplete
    - python-pptx
    - python-docx
    - pdfminer
    - beautifulsoup4

  run:
    - python
    - argcomplete
    - python-pptx
    - python-docx
    - pdfminer
    - beautifulsoup4

test:
  # Python imports
  imports:
    - textract.parsers
    - textract

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/deanmalmgren/textract
  license: 
  summary: 'extract text from any document. no muss. no fuss.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
