package:
  name: pytest
  version: !!str 2.6.1

source:
  fn: pytest-2.6.1.tar.gz
  url: https://pypi.python.org/packages/source/p/pytest/pytest-2.6.1.tar.gz
  md5: bb353f6cf6d9ff83ff7f2dfbeaca47a3
#  patches:
   # List any patch files here
   # - fix.patch

build:
  #preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pytest = pytest:main
    #
    # Would create an entry point called pytest that calls pytest.main()

    - py.test = pytest:main
    - py.test-2.7 = pytest:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - py

  run:
    - python
    - py

test:
  # Python imports
  imports:
    - _pytest
    - pytest
    - _pytest.assertion

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - py.test --help
    - py.test-2.7 --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pytest.org
  license: MIT License
  summary: 'pytest: simple powerful testing with Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
